data:
  images_path: "/media/steve/Seagate Portable Drive/datasets/coco/train2014"
  annotations_file: "/media/steve/Seagate Portable Drive/datasets/coco/annotations/instances_train2014.json"
  num_train_images: 10000  # Keep high enough to ensure that at least one of each label is seen in training. 2500 is a good minimum
  num_test_images: 500

training:  # Includes eval params
  n_epochs: 20
  learning_rate: 3e-6  # Keep very low
  save_eval_images: false
  use_class_weight: false  # performance seems worse with class weight, keep false
  weight_decay: 0.1  # torch default is 0.01
  
  # NOTE: Use these values for benchmarking to stay consistent with YOLO, fasterRCNN, SSD, DETR,... etc
  #   confidence_threshold: 0.001 - 0.01  
  #   iou_threshold: 0.45 - 0.06
  confidence_threshold: 0.01
  iou_threshold: 0.6  # For nms

  
  
